name: Maven Build and Sign
on:
  push:
    branches:
      - main
      
env:
  PROJECT_NAME: HelloWorld
  PROJECT_VERSION: 0.0.1

jobs:
  build-and-sign-exe:
    runs-on: ubuntu-latest
    name: Build and Sign Executable on Java with Maven
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Maven and Java
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 17
          maven-version: 3.8.5

      - name: Create Directories
        run: |
          mkdir -p artifacts
          mkdir -p packages
          mkdir -p certs

      - name: Build Java Project
        run: |
          mvn clean install -f pom.xml
          cp target/HelloWorld-0.0.1-SNAPSHOT.jar packages/HelloWorld.jar

      - name: Generate Private Key
        run: |
          openssl genpkey -algorithm RSA -out certs/private.key -pkeyopt rsa_keygen_bits:2048

      - name: Generate CSR
        run: |
          openssl req -new -key certs/private.key -out certs/request.csr -subj "/C=US/ST=California/L=San Francisco/O=Example Company/OU=IT Department/CN=example.com"
      
      - name: Self-Sign CSR to create self-signed certificate
        run: |
          openssl x509 -req -days 180 -in certs/request.csr -signkey certs/private.key -out certs/self-signed-certificate.crt

      - name: Create Java Keystore
        run: |
          keytool -genkeypair -alias myalias -keyalg RSA -keysize 2048 -validity 180 -keystore certs/keystore.jks -storepass changeit -keypass changeit -dname "CN=Your Name, OU=Your Organization, O=Your Company, L=Your City, ST=Your State, C=Your Country"

      - name: Sign JAR
        run: |
          jarsigner -keystore certs/keystore.jks -storepass changeit -keypass changeit packages/HelloWorld.jar myalias

      - name: Verify JAR Signature
        run: |
          jarsigner -verify packages/HelloWorld.jar

      - name: Install jpackage
        run: |
          sudo apt-get update
          sudo apt-get install -y jpackage

      - name: Create Executable
        run: |
          jpackage \
            --input packages \
            --name HelloWorld \
            --main-jar HelloWorld.jar \
            --main-class com.example.MainClass \
            --type app-image \
            --dest packages

      - name: Create EXE using jpackage
        run: |
          jpackage \
            --input packages \
            --name HelloWorld \
            --main-jar HelloWorld.jar \
            --main-class com.example.MainClass \
            --type exe \
            --dest packages

      - name: Upload Executable File
        uses: actions/upload-artifact@v2
        with:
          name: HelloWorld.exe
          path: packages/HelloWorld.exe
