name: Maven Build and Sign
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: HelloWorld
  PROJECT_VERSION: 0.0.1

jobs:
  build-and-sign-exe:
    runs-on: ubuntu-latest
    name: Build and Sign Executable on Java with Maven
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Maven and Java
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 17
          maven-version: 3.8.5
          
      - name: Create Directories
        run: |
          mkdir -p artifacts
          mkdir -p packages
          mkdir -p certs

      - name: Install Exe4j
        run: |
          wget https://download.ej-technologies.com/exe4j/exe4j_unix_9_0.tar.gz
          tar -xzf exe4j_unix_9_0.tar.gz
          sudo mv exe4j9 /opt/exe4j

      - name: Set Exe4j Path
        run: echo "EXE4J_PATH=/opt/exe4j/bin/exe4j" >> $GITHUB_ENV

      - name: Print Exe4j Path
        run: echo $EXE4J_PATH

      - name: Build Project and Create Executable
        run: |
         mvn -D exe4j.path=$EXE4J_PATH clean package
         cp target/HelloWorld-0.0.1-SNAPSHOT.jar packages/HelloWorld.jar

      - name: List target directory
        run: ls -al target

      - name: Upload Executable File
        uses: actions/upload-artifact@v2
        with:
          name: HelloWorld.exe
          path: target/HelloWorld.exe
          # path: target/maven-archiver

