# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-sign-jar:
    runs-on: ubuntu-latest
    name: code signer on Java with Maven
    steps:
      - uses: actions/checkout@v2
      - name: Install Maven and Java
       
        with:
          java-version: '${{env.JAVA_VERSION}}'
          maven-version: '${{env.MAVEN_VERSION}}'
      - name: Create Directory
        shell: bash
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifacts
          mkdir ${GITHUB_WORKSPACE}/packages
      - name: Build Java Project
        shell: bash
        run: |
          mvn clean install -f java/pom.xml
          cp java/target/${{env.PROJECT_NAME}}-${{env.PROJECT_VERSION}}.jar ${GITHUB_WORKSPACE}/packages/${{env.PROJECT_NAME}}.jar

      - name: Sign Artifact
        uses: sslcom/actions-codesigner@develop
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: ${{secrets.CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: ${GITHUB_WORKSPACE}/packages/${{env.PROJECT_NAME}}.jar
          output_path: ${GITHUB_WORKSPACE}/artifacts

      - name: Upload Signed Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.PROJECT_NAME}}.jar
          path: ./artifacts/${{env.PROJECT_NAME}}.jar


env:
  PROJECT_NAME: HelloWorld
  PROJECT_VERSION: 0.0.1
  MAVEN_VERSION: 3.8.5
  JAVA_VERSION: 17
